### ISSUE TITLE
Support GL raster backend

### ISSUE THREAD

**Issue by hermet** [thorvg/thorvg#1687] opened 2023-10-05 05:11 UTC
The current gl engine is under development; the features are unstable, and its coverage is quite low.

Confirmed example working

- [x] Shape
- [x] MultiShapes
- [x] Path
- [x] PathCopy
- [x] Scene
- [x] Transform
- [x] Accessor
- [x] CustomTransform
- [x] Animation
- [x] Update
- [x] PictureSvg
- [x] DataLoad
- [x] LinearGradient
- [x] RadialGradient
- [x] PictureJpg
- [x] PicturePng
- [x] PictureWebp
- [x] SceneTransform
- [x] GradientTransform
- [x] FillRule
- [x] ImageScaleDown
- [x] ImageScaleUp
- [x] Arc
- [x] StrokeLine
- [x] DirectUpdate
- [x] Text
- [x] Retaining
- [x] Stroke
- [x] AnimateMasking
- [x] InvLumaMasking
- [x] FillSpread
- [x] PictureRaw
- [x] InvMasking
- [x] SceneBlending
- [x] Masking
- [x] LumaMasking
- [x] GradientMasking
- [x] ClipPath
- [x] LottieExtensions
- [x] Opacity
- [x] MaskingMethods
- [x] Texmap
- [x] GradientStroke
- [x] Svg
- [x] Tvg
- [ ] StrokeMiterLimit
- [ ] Performance
- [ ] Viewport
- [ ] StrokeTrim
- [ ] Duplicate
- [ ] Blending
- [ ] PictureTvg
- [ ] Lottie

**Comment by hermet** [comment] 2023-10-05 05:12
https://github.com/thorvg/thorvg/pull/1531

**Comment by hermet** [comment] 2023-10-20 02:21
https://github.com/thorvg/thorvg/pull/1704

**Comment by hermet** [comment] 2023-12-27 07:45
Radial Gradient fill is somewhat different.
![shot-2023-12-27_16-44-51](https://github.com/thorvg/thorvg/assets/3711518/8ecadd48-a432-4b9b-b53d-866b3df6a7bd)

**Comment by hermet** [comment] 2023-12-27 07:48
@RuiwenTang Radial Gradient fill is a bit different. I remember it worked properly before?
![shot-2023-12-27_16-44-51](https://github.com/thorvg/thorvg/assets/3711518/8ecadd48-a432-4b9b-b53d-866b3df6a7bd)

**Comment by hermet** [comment] 2023-12-27 07:51
Retaining doesn't updated.

**Comment by RuiwenTang** [comment] 2023-12-27 07:52
Maybe my recent commit broke it, I'll check

**Comment by hermet** [comment] 2023-12-27 07:58
Masking samples appear to be mostly working well, although some overlaid or background colors are not appropriate.

**Comment by hermet** [comment] 2024-02-22 03:43
@RuiwenTang @SergeyLebedkin Hello, do you mind any anti-aliasing (AA) techniques for GL backend? We plan to implement this with WebGPU and it would be beneficial if the same methodology could be applied. Our primary is MSAA.

**Comment by hermet** [comment] 2024-02-22 04:04
Condition check:
These are basically working but some minor differences are observed.

- radial gradient: background(bg) color must be black (not gray)
![radial_gradient](https://github.com/thorvg/thorvg/assets/3711518/728f78e3-5d55-42ff-9011-fcbe668f2325)

- The colors of these masks appear to be somewhat weakened.
![gradient masking](https://github.com/thorvg/thorvg/assets/3711518/bb45ec23-8b51-40c8-a849-67c81b3d6d6e)
![masking](https://github.com/thorvg/thorvg/assets/3711518/7260153d-8e40-4914-90f4-5d9ea757f234)
![inverse masking](https://github.com/thorvg/thorvg/assets/3711518/7d0ade59-38bd-4e76-a0e3-f5fa8a2ac774)

**Comment by RuiwenTang** [comment] 2024-02-22 04:46
> @RuiwenTang @SergeyLebedkin Hello, do you mind any anti-aliasing (AA) techniques for GL backend? We plan to implement this with WebGPU and it would be beneficial if the same methodology could be applied. Our primary is MSAA.

I also prefer MSAA which is more efficient in modern GPU APIs like vulkan, metal or WebGPU

**Comment by lostminds** [comment] 2024-03-01 11:37
Would it be possible use this faster (I assume) rendering backend in parallell with the regular SW-engine, and have ThorVG automatically pick renderer to use based on what features the content drawn requires? 

This way we could benefit from the performance improvements of this renderer for rendering more basic content, while it would fall back to the regular SW renderer in case features are required that the GL renderer doesn't yet support.

**Comment by hermet** [comment] 2024-03-01 17:52
@lostminds Thanks for suggestion. Still, it needs more attention and development. Perhaps AA (Anti-Aliasing) should be applied before basic practical usage. I'd like to suggest that you can test for specific drawing contents and then decide which backend engine would be more efficient for your project (rather than fallback mechanism). btw, I'm really wondering the software renderer is not suitable for your project due to performance concerns.

**Comment by lostminds** [comment] 2024-03-02 08:47
> btw, I'm really wondering the software renderer is not suitable for your project due to performance concerns.

My use-case is probably a bit unusual, I'm using ThorVG via Godot in a [parametric graphic design app](https://paragraphic.design) I'm building. It both imports and exports SVG and uses an SVG-like internal format. So I use ThorVG to render a preview of each layer, re-rendering the layers separately on a separate thread when they change and composit them together as textures in Godot. The performance is ok, but could of course be better.

The reason I proposed the automatic renderer selection/fallback-model is that since the content in my case is controlled by the user, I can't know what it will be. It could for example include imported SVG files, so I would like to have as close to full SVG support as possible since fidelity is more important than performance. However, in many cases the content will likely be just a lot of simple filled or stroked shapes. And for these cases it would be nice to get something more performant like GPU-based rendering since in this case the more complex features are not required. But I understand very well that it's a big task, and like you say, getting a good AA solution in place first will likely be needed for any practical use.

**Comment by hermet** [comment] 2024-03-03 07:16
> However, in many cases the content will likely be just a lot of simple filled or stroked shapes. And for these cases it would be nice to get something more performant like GPU-based rendering since in this case the more complex features are not required.

I completely understand your point. However, after considering the conditions you mentioned, you can always use the ThorVG GL engine once anti-aliasing (AA) is implemented. Nevertheless, Godot also needs to consider the ThorVG GL version, a topic that has not yet been discussed on the Godot side. Let me look into this further.

**Comment by hermet** [comment] 2024-03-12 10:07
@RuiwenTang, wrt https://github.com/orgs/thorvg/discussions/2048, I think we need to think about the GL integration now. Currently, `glCanvas` has parameters:

```
GlCanvas::target(uint32_t* buffer, uint32_t stride, uint32_t w, uint32_t h)
```

The `buffer` is not actually used; however, I assume we can replace it with `fbo(id)`:

```
GlCanvas::target(uint32_t targetID, uint32_t stride, uint32_t w, uint32_t h)
```

Basically, we expect the `targetID` to be a valid FBO, which we can bind inside the GL renderer. If the FBO is invalid or 0, we can probably assume the rendering target is main surface, and we can perform the drawing directly.

What do you think?

**Comment by RuiwenTang** [comment] 2024-03-12 10:39
> @RuiwenTang, wrt https://github.com/orgs/thorvg/discussions/2048, I think we need to think about the GL integration now. Currently, `glCanvas` has parameters:
> 
> ```
> GlCanvas::target(uint32_t* buffer, uint32_t stride, uint32_t w, uint32_t h)
> ```
> 
> The `buffer` is not actually used; however, I assume we can replace it with `fbo(id)`:
> 
> ```
> GlCanvas::target(int32_t targetID, uint32_t stride, uint32_t w, uint32_t h, Colorspace cs)
> ```
> 
> Basically, we expect the `targetID` to be a valid FBO, which we can bind inside the GL renderer. If the FBO is invalid or 0, we can probably assume the rendering target is main surface, and we can perform the drawing directly (with no threading).
> 
> What do you think?

It looks good to me. 👍

**Comment by hermet** [comment] 2024-04-01 06:30
@RuiwenTang Hello, with the latest gl backend, it aborted by the glBlitFramebuffer().
```
[E] GL_ENGINE (../src/renderer/gl_engine/tvgGlRenderTask.cpp 223): glGetError() = 1282 (0x00000502)
Shape: ../src/renderer/gl_engine/tvgGlRenderTask.cpp:223: virtual void GlBlitTask::run(): Assertion `0' failed.
```
Guess due to the latest updates, I haven't delved deeply into it, but I wonder if I've missed a setup step. Any idea?

**Comment by RuiwenTang** [comment] 2024-04-01 07:15
> @RuiwenTang Hello, with the latest gl backend, it aborted by the glBlitFramebuffer().
> 
> ```
> [E] GL_ENGINE (../src/renderer/gl_engine/tvgGlRenderTask.cpp 223): glGetError() = 1282 (0x00000502)
> Shape: ../src/renderer/gl_engine/tvgGlRenderTask.cpp:223: virtual void GlBlitTask::run(): Assertion `0' failed.
> ```
> 
> Guess due to the latest updates, I haven't delved deeply into it, but I wonder if I've missed a setup step. Any idea?
> 
> FYI, my OpenGLES profile version is 3.2.

Maybe the freamebuffer is wrong, but I don't have EFL runtime envrionment and can't reproduce this error ...

**Comment by RuiwenTang** [comment] 2024-04-01 07:35
> @RuiwenTang the EFL are available on most distro and even on Windows. I think it is not very difficult to install them

My most common development is MacOS, I tried it remember?
https://github.com/thorvg/thorvg/pull/1531#issuecomment-1646832388

**Comment by vtorri** [comment] 2024-04-01 07:40
arg, i would be glad to fix it but I have no mac :(

**Comment by vtorri** [comment] 2024-04-01 07:58
ok, i've looked at the evas gl_cocoa module code. Nothing has been done for opengl on mac.
I think that it would not be difficult to port : EGL will help from cross platform code (I did that for win32 a long time ago). Some macOS code should be done though.

**Comment by hermet** [comment] 2024-04-01 09:25
@RuiwenTang Thanks, I thought you used the example code with EFL directly, Just one simple request for 0.13 release. Could you please make sure the above feature coverage check boxes? We need to update with the latest condition.

**Comment by RuiwenTang** [comment] 2024-04-02 04:46
> @RuiwenTang Thanks, I thought you used the example code with EFL directly, Just one simple request for 0.13 release. Could you please make sure the above feature coverage check boxes? We need to update with the latest condition.

I update some states above. 

> BTW. I use glfw for window creation and angle for mock OpenGLES on MacOS

**Comment by vtorri** [comment] 2024-04-02 05:41
you should use Metal :)

**Comment by hermet** [comment] 2024-04-02 08:31
@RuiwenTang Thanks. btw, I believe this issue should be properly addressed. All context has been transferred to the ThorVG GL backend, preventing EFL from interrupting the framebuffers. This might be an issue that breaks the thorvg gl compatibility with other systems.

**Comment by RuiwenTang** [comment] 2024-04-02 08:45
@hermet I think the GL backend code can work normally when passing in the correct framebuffer ID. 
I suspect that the execution timing of initGLview is too early, resulting in the obtained framebuffer ID not corresponding to GLView.
> BTW, I don't like EFL, as a window toolkit it seems too heavy

**Comment by hermet** [comment] 2024-04-02 08:54
@RuiwenTang what is the correct framebuffer ID? gl backed worked properly with the thorvg example code until the latest your patch.

**Comment by RuiwenTang** [comment] 2024-04-02 09:00
@hermet https://github.com/thorvg/thorvg/pull/2049 this patch changed the timing of obtaining framebuffer ID. The final color blit code is merged before https://github.com/thorvg/thorvg/pull/2040

**Comment by hermet** [comment] 2024-04-02 09:01
@RuiwenTang Ah I forgot that one. thanks for your cooperation. I will review it again.

**Comment by hermet** [comment] 2024-04-02 09:05
@RuiwenTang If the framebuffer ID is zero, won't the GL backend draw onto the main surface?

**Comment by RuiwenTang** [comment] 2024-04-02 09:16
@hermet Yes, fbo ID zero means target on the screen, but `GL_INVALID_OPERATION ` aka 0x502  may be caused by many factors. If the fbo ID is correct, maybe this fbo enabled msaa? I can't debug so I can only guess :(

**Comment by hermet** [comment] 2024-04-03 06:12
Two checks from my side: 
- PictureRaw: it has no clipping effect.
- MaskingMethods: anti-aliased edges are blended incorrectly.

**Comment by hermet** [comment] 2024-04-14 15:41
With the lastest test: 3 examples are broken.
- Arc:
![image](https://github.com/thorvg/thorvg/assets/3711518/e16b6509-c255-4d3f-82d2-c40d5c5df1a8)
- ImageScaleUp: texture(image) is empty(black)
- ImageScaleDown: texture(image) is empty(black)

**Comment by RuiwenTang** [comment] 2024-04-15 05:19
> With the lastest test: 3 examples are broken.
> 
>     * Arc:
>       ![image](https://private-user-images.githubusercontent.com/3711518/322285081-e16b6509-c255-4d3f-82d2-c40d5c5df1a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTg2MDMsIm5iZiI6MTcxMzE1ODMwMywicGF0aCI6Ii8zNzExNTE4LzMyMjI4NTA4MS1lMTZiNjUwOS1jMjU1LTRkM2YtODJkMi1jNDBkNWM1ZGYxYTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMDUxODIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZkM2NhNWM5MzIyNDU1YTE3ODkyMGQwMjJlZTI3M2JlOTc5YjVmNzE3Y2Y1MTgwMDFhZDU4NDc3NDVhNjNjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1AOImVyj7mQyHH3bJueifrqt6qnvcyKbvJJm0mXDMuc)
> 
>     * ImageScaleUp: texture(image) is empty(black)
> 
>     * ImageScaleDown: texture(image) is empty(black)

#2181 This PR fix the rendering error in *ImageScaleUp* and *ImageScaleDown*

**Comment by hermet** [comment] 2024-05-01 10:41
GradientStroke has a single gap between shapes:
![image](https://github.com/thorvg/thorvg/assets/3711518/e49ece6a-736b-429c-8a0c-a70a1ae728b9)
Current SVG rendering output:
![image](https://github.com/thorvg/thorvg/assets/3711518/ffa07e5b-bc5e-4410-bb5a-fc288a98f7b5)

**Comment by RuiwenTang** [comment] 2024-05-01 11:05
> GradientStroke has a single gap: ![image](https://private-user-images.githubusercontent.com/3711518/327105576-e49ece6a-736b-429c-8a0c-a70a1ae728b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjE3NjUsIm5iZiI6MTcxNDU2MTQ2NSwicGF0aCI6Ii8zNzExNTE4LzMyNzEwNTU3Ni1lNDllY2U2YS03MzZiLTQyOWMtOGEwYy1hNzBhMWFlNzI4YjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMTEwNDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDg5OWY3ZGFmMjQ4MmYwZGExYmQ5MzNiNjBkYTBkZWQwNjk4NTM4ODllOTRlNGQwZmI3YTU4N2UwNjAzMzI0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FIvAjPjC-WK0TzRc4mj9cF4a1Yx9p5x_O7-HynQHXXA) Current SVG rendering output: ![image](https://private-user-images.githubusercontent.com/3711518/327105792-ffa07e5b-bc5e-4410-bb5a-fc288a98f7b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NjE3NjUsIm5iZiI6MTcxNDU2MTQ2NSwicGF0aCI6Ii8zNzExNTE4LzMyNzEwNTc5Mi1mZmEwN2U1Yi1iYzVlLTQ0MTAtYmI1YS1mYzI4OGE5OGY3YjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMTEwNDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDM3ZGVhZjg1Njc5ZDdhYmIzOWFmOTJmMGEzMzkyOTc2ODBkMTg2NTU1NTBkNDU0N2YzOTQ2NDU0NzYzMGFhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6Ec6-kU6fKBkuowvfYpFrBs05mrobYiKPBR-6cCBvQk)

The stencil reference is wrong, I fixed at #2236

**Comment by hermet** [comment] 2024-06-04 07:09
Progress Check:
- Opacity/SceneBlending has regressions (clipped scene in a wrong way)
![shot-2024-06-04_15-53-16](https://github.com/thorvg/thorvg/assets/3711518/26888a89-0ea7-4211-bf62-c88b91620b1a)

- GradientStroke still has a single gap:
![image](https://github.com/thorvg/thorvg/assets/3711518/68f16d64-b1e0-43f1-83e2-5c445cc9764f)

-Stroke Width looks bolder (See lines near mouth)
![shot-2024-06-04_16-01-28](https://github.com/thorvg/thorvg/assets/3711518/8fc6bca7-57fb-4b61-90fe-279d53fbe6dc)

@RuiwenTang btw, the GL engine has been greatly improved. I really appreciate your continued effort!

**Comment by RuiwenTang** [comment] 2024-06-08 00:51
@hermet 
I checked the `AnimateMasking` example rendered by software raster, the behavior is same as GL backend, I think the problem is not caused by rendering engine, please check the issue:
![image](https://github.com/thorvg/thorvg/assets/26308154/c6151390-0421-4a3b-9666-d96b571b78e2)

**Comment by hermet** [comment] 2024-06-08 09:31
@RuiwenTang It doesn't make sense to me; the rendering result is not related to the ThorVG rendering engine. Do you think the OpenGL version could affect stroke width?

**Comment by hermet** [comment] 2024-06-20 11:03
Examples Pass Rate: 85%

**Closed** 2024-06-21 01:58 UTC
Labels: feature, raster
